
services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/product.sql:/docker-entrypoint-initdb.d/product.sql
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 20s 
      timeout: 12s
      retries: 10 


  express-app:
    build: .
    container_name: my_express_app
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=abc123
      - DB_DATABASE=mydb
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  pg_data: